### ISSUE TITLE
Chroma Dark appears to be Light on Alcatraz

### ISSUE THREAD

**Issue by l4u** [danielb5/chroma-theme#2]
![Chroma](http://i.imgur.com/guH24AC.png)

**Comment by danielb5** [comment]
I checked and everything is correct. Wrong cached image? Try reloading packages

**Comment by l4u** [comment]
I've tried removing it and installing it again.
Xcode was restarted too.

![](http://i.imgur.com/xzuagp9.png)

**Comment by l4u** [comment]
If I install the theme manually, the dark theme works.
If I reinstall it with Alcatraz, it turns light.

**Comment by danielb5** [comment]
You're right, there was a problem with the url... Shouldn't take long for the package to be updated in Alcatraz.
Thanks for the feedback :) !
